bin/magento setup:install \
--base-url=http://magento \
--db-host=localhost \
--db-name=magento \
--db-user=admin \
--db-password=123456 \
--admin-firstname=admin \
--admin-lastname=admin \
--admin-email=admin@admin.com \
--admin-user=admin \
--admin-password=admin123 \
--language=en_US \
--currency=USD \
--timezone=America/Chicago \
--use-rewrites=1
